name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: macos-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v3

    - name: Tags fetching
      run: git fetch --tags

    - name: Main branch and latest commit tag check
      run: |
        if [ $(git rev-parse --abbrev-ref HEAD) = "main" ]; then
            if git describe --exact-match --tags $(git rev-parse HEAD); then
                echo "Latest commit has tag."
                exit 0
            fi
        fi

    - name: Last tag definition
      run: |
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

    - name: Version increment
      run: |
        if [ -z "$LATEST_TAG" ]; then
          VERSION="0.0.0"
        else
          VERSION=$(echo $LATEST_TAG | awk -F. '{print $1"."$2"."$3+1}')
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Tag creation
      run: |
        git tag "$VERSION"
        git push origin "$VERSION"
